# Generated by Django 5.0.7 on 2024-08-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
