# Generated by Django 5.0.7 on 2024-08-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_title_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='group',
            new_name='type',
        ),
    ]
