# Generated by Django 5.0.7 on 2024-08-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_group_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='label',
        ),
    ]
